// prettier-ignore
const MECHANICS = [
  '%AOE%',
  '%ARMOR%',
  '%BOON%',
  '%BUBBLE%',
  '%BUFF%',
  '%BULWARK%',
  '%CANT_TARGET%',
  '%CHOOSE_ONE%',
  '%COMBO%',
  '%DEBUFF%',
  '%DESTROY%',
  '%DISABLE%',
  '%DISCOVER%',
  '%DOUBLE_ATTACK%',
  '%DRAW_CARD%',
  '%ENERGY_CRYSTAL%',
  '%ENERGY%',
  '%EXPIRATION%',
  '%HIDDEN%',
  '%IMMUNE%',
  '%LIFESTEAL%',
  '%MYSTERY%',
  '%NO_ATTACK%',
  '%ON_DEATH%',
  '%ON_PLAY%',
  '%OVERLOAD%',
  '%POISON%',
  '%RANDOM%',
  '%RESTORE_HP%',
  '%RUSH%',
  '%SET_VALUE%',
  '%SILENCE%',
  '%SPELL_DAMAGE%',
  '%STEAL%',
  '%SUMMON%',
  '%TARGETED_SPELL%',
  '%TRANSFORM%',
];

export default MECHANICS;
